services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpArsenal\MythologicalUsernameGeneratorBundle\UsernameGenerator:
    factory: [PhpArsenal\MythologicalUsernameGeneratorBundle\UsernameGeneratorFactory, build]